sudo: required
language: generic
services:
- docker
env:
  matrix:
  - ver=0.4.0
  global:
  # DOCKER_USERNAME
  - secure: uZsdlrrBQLfaSQB73rQ2wh00/Rnnu2iuTQfstqnA1AcK36GUbPIIfN/PyL4wMpuGwLI2ZKJPaywwJ0LfzmOfxl7ZiN7KQVO3NNtcIZAKx7u/W7P2HMNe+NhF/8qyukCPu9D54ph+Z9qjL8RmhJsDc+JqbXBIAqsLazF03Jtzun6dTOsapsPSq+8mTPSAQzRA24QxzaDeL0yzsTMPNZdihb4k3gIGwWeGJZx18NQtEi+MEdi+Qocqw5yndRI+j0UvbDi51pvO8rn94nnN8/o4c7M2XCi3JbmmnLTJJFnvktokrh06cXqTuZk6IE6+4pkgMdKPzZWgleVeuN06iEULS5fMfg+EBCJKXG9aV0WH1Tpok7Fz12OW1P+EOMyJHamGl7juGSubceeegbBBy4DDFYP9SqUW3uOOq+0X/jo5PLt4Ewmv7O1A2AvUeHXNYGWwJG7acKWkULUUeRKO8DryIQb92+TwtjFjDI4MX49A3nhabt/cFOukNuT/PxttY99cEqd0p3Eqt2KJiGalbPw1MqrzyPM25k51AIbMhFL/Co9SYVgkw8y9yCZUWFcZd4KujilMJBG+mR4Ii+4K0AJZmhbbP+yK8tBbUU6A1utG96Az4fNtCwZ08EucbaJCQ5TE1K2sqKWRiEWOqya/iXmcKzyM4sGTxhN76HOeDtQQez8=
  # DOCKER_PASSWORD
  - secure: mP36FGgldmT365e9y4g5gp1/C+X6NAJBZYHyT0q3LnOJ+u3m3B3WONfJU7S9yOWjeEfEfPmh4NJk7X3GF7mQ8sCTRR3m88RqOc5BHrbl7JdrQqPLeJvstfRQznXN8GG+J3j4zMD7WBonzjjREgY2FN/54+0el+3BX1L3N9HEi5J4MXyRty6JoGe9f1GZ+1Oqky2mED8YP8eqCwNAMGF0cifJ9pd7wG57/DZ95QfjFM3YQ4pAGz5QQBSwpQ9sMobrGrgcHimBvBb2DEhNXIxd6yXrQ0jQFj/kqMvcgbGE7IU29XBDM8mgVdxHvdTIdZJlDNBGEXWbhOVyBcTMabQ4k4GG/AWHvhl3781sOMwNvRAIrmZ04ZbtK2DroufhAA6HhiCqB/T0OozKTfd8mZDaaYHBbbczQ0dTPYTytxcoeEAJDWIuZmXMhzKuF9mx+EGkHwwBQhJCrjA998GHhTj1HDHqX6/QZ731UlWUi2lARU1NUe2QInDaGbHBM5TkxEonWTF1LjCgfAizC26oaSIcOLowMi9Svrt+LDl5U/jb8SaTs18qak9OuVNpgpH5BfkljTQVji1meuJ01gHynJVOeRT0izOeUroioYyPKBx7UVMsww1YY+/Pt+c/qTSuLSnbwp1WEzloSOEXYW5Dh6z/DusraYohA0tOisboVelSYmI=
script:
- make build
- make test
deploy:
- provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make deploy
  on:
    branch: master
